const Class = require("../models/Class");

/* ================= CREATE CLASS (TEACHER) ================= */
exports.createClass = async (req, res) => {
  try {
    // 🔐 Only teachers allowed
    if (req.user.role !== "teacher") {
      return res.status(403).json({
        message: "Only teachers can create classes",
      });
    }

    const { name, subject, startTime, endTime } = req.body;

    // ✅ Validate input
    if (!name || !subject || !startTime || !endTime) {
      return res.status(400).json({
        message: "All fields are required",
      });
    }

    // ✅ Create class (classCode is auto-generated by schema)
    const newClass = await Class.create({
      name,
      subject,
      startTime,
      endTime,
      teacher: req.user.id,
    });

    res.status(201).json({
      message: "Class created successfully",
      class: newClass,
    });
  } catch (err) {
    console.error("CREATE CLASS ERROR:", err);
    res.status(500).json({
      message: "Failed to create class",
    });
  }
};

/* ================= GET CLASSES ================= */
/*
  Teacher → only own classes
  Student → all classes
*/
exports.getClasses = async (req, res) => {
  try {
    let classes;

    if (req.user.role === "teacher") {
      classes = await Class.find({ teacher: req.user.id })
        .populate("teacher", "name email role")
        .sort({ createdAt: -1 });
    } else {
      classes = await Class.find()
        .populate("teacher", "name email role")
        .sort({ createdAt: -1 });
    }

    res.json(classes);
  } catch (err) {
    console.error("FETCH CLASSES ERROR:", err);
    res.status(500).json({
      message: "Failed to fetch classes",
    });
  }
};

/* ================= JOIN CLASS (STUDENT/TEACHER) ================= */
exports.joinClass = async (req, res) => {
  try {
    const { classId } = req.body;

    // ✅ Validate input
    if (!classId) {
      return res.status(400).json({
        message: "Class ID is required",
      });
    }

    const classroom = await Class.findById(classId);

    if (!classroom) {
      return res.status(404).json({
        message: "Class not found",
      });
    }

    // ✅ Prevent double join
    if (classroom.students.some(s => s.toString() === req.user.id)) {
      return res.status(400).json({
        message: "Already joined this class",
      });
    }

    classroom.students.push(req.user.id);
    await classroom.save();

    res.json({
      message: "Joined class successfully",
    });
  } catch (err) {
    console.error("JOIN CLASS ERROR:", err);
    res.status(500).json({
      message: "Failed to join class",
    });
  }
};
